export type AppActionType =
  | 'addonsRefreshRequested'
  | 'calendarMonthRequested'
  | 'clearPlaybackProgressRequested'
  | 'detailLoadRequested'
  | 'detailSeasonRequested'
  | 'detailStreamsRequested'
  | 'discoverRequested'
  | 'enginePing'
  | 'homeLoadRequested'
  | 'refreshContinueWatchingRequested'
  | 'libraryAddRequested'
  | 'libraryHydrateRequested'
  | 'markWatchedRequested'
  | 'savePlaybackProgressRequested'
  | 'searchRequested'
  | 'settingsChanged'
  | 'syncExternalIntegration'
  | 'toggleLibraryStatusRequested'
  | 'toggleWatchlistRequested';

export interface AppAction<TPayload extends Record<string, unknown> = Record<string, unknown>> {
  type: AppActionType;
  [key: string]: unknown;
  payload?: TPayload;
}

export type EffectType =
  | 'clearPlaybackProgress'
  | 'enqueueOfflineDownload'
  | 'enqueueTraktScrobble'
  | 'exchangeAuthCode'
  | 'fetchAddonManifest'
  | 'fetchAddonResource'
  | 'fetchCatalogPage'
  | 'fetchDetailSecondary'
  | 'fetchDetailStreams'
  | 'fetchIntroSegments'
  | 'fetchMetaDetail'
  | 'fetchMetaDetailLookup'
  | 'fetchSeasonEpisodes'
  | 'fetchSubtitles'
  | 'loadStreams'
  | 'notifyReleasedEpisodes'
  | 'prefetchDetailStreams'
  | 'prepareDirectPlayback'
  | 'readCalendarMonth'
  | 'readDetailLocalState'
  | 'readDiscoverCatalogFilters'
  | 'readHomeBootstrap'
  | 'refreshContinueWatching'
  | 'readLibraryState'
  | 'readPlaybackProgress'
  | 'refreshAuthToken'
  | 'refreshInstalledAddons'
  | 'replaceExternalContinueWatching'
  | 'resolveIntroImdbId'
  | 'runAuthFlow'
  | 'runDiscover'
  | 'runExternalSync'
  | 'runSearch'
  | 'startTorrentStream'
  | 'stopTorrent'
  | 'syncExternalIntegration'
  | 'syncWatchedState'
  | 'updateCalendarWidget'
  | 'writeFeedback'
  | 'writeLibraryCommand'
  | 'writePlaybackProgress'
  | 'writeSettings';
