import type React from 'react';

export const NAV_RAIL_WIDTH = 6.5;

const FONT = "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
export { FONT };

export const styles: Record<string, React.CSSProperties> = {
  screen: {
    height: '100%',
    background: '#0C0C0C',
    overflow: 'hidden',
    padding: `2rem 3rem 2.5rem ${NAV_RAIL_WIDTH + 1.75}rem`,
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: '16.75rem 1fr',
    gap: '2rem',
    alignItems: 'stretch',
  },
  sidebar: {
    minWidth: 0,
    height: '100%',
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  sidebarTitle: {
    color: '#FFFFFF',
    fontSize: '1.375rem',
    fontWeight: 700,
    margin: '0 0 0.25rem',
    fontFamily: FONT,
    lineHeight: 1,
    letterSpacing: '-0.025em',
  },
  sidebarSubtitle: {
    color: 'rgba(255,255,255,0.28)',
    fontSize: '0.625rem',
    margin: '0 0 1.125rem 1px',
    fontFamily: FONT,
    lineHeight: 1.35,
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.09em',
  },
  content: {
    minWidth: 0,
    height: '100%',
    overflowY: 'auto',
    padding: '0 0.625rem 6rem 0',
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255,255,255,0.1) transparent',
  },
  categoryCard: {
    width: '100%',
  },
  categoryIcon: {
    width: '2.25rem',
    height: '2.25rem',
    borderRadius: '0.5625rem',
    background: 'rgba(255,255,255,0.07)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  categoryLabel: {
    display: 'block',
    color: 'rgba(255,255,255,0.90)',
    fontSize: '0.875rem',
    fontWeight: 600,
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: FONT,
  },
  categorySubtitle: {
    display: 'block',
    color: 'rgba(255,255,255,0.36)',
    fontSize: '0.6875rem',
    lineHeight: '0.9375rem',
    fontWeight: 400,
    marginTop: '0.125rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: FONT,
  },
  chevronIcon: {
    display: 'flex',
    color: 'rgba(255,255,255,0.22)',
    flexShrink: 0,
  },
  mobileDivider: {
    height: 1,
    background: 'rgba(255,255,255,0.045)',
    marginLeft: '3.625rem',
  },
  versionFooter: {
    color: 'rgba(255,255,255,0.25)',
    fontSize: '0.6875rem',
    fontWeight: 400,
    fontFamily: FONT,
    textAlign: 'center',
    margin: '0.875rem 0 0',
    letterSpacing: '0.04em',
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    minHeight: '2.25rem',
    marginBottom: '1.375rem',
    paddingBottom: '1.125rem',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  detailTitle: {
    color: '#FFFFFF',
    fontSize: '1.375rem',
    fontWeight: 700,
    margin: 0,
    fontFamily: FONT,
    lineHeight: 1,
    letterSpacing: '-0.025em',
  },
  settingsGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.375rem',
    marginBottom: '1.5rem',
  },
  groupHeading: {
    paddingLeft: '0.25rem',
  },
  groupTitle: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: '0.6875rem',
    fontWeight: 600,
    margin: 0,
    fontFamily: FONT,
    textTransform: 'uppercase',
    letterSpacing: '0.07em',
  },
  groupSubtitle: {
    color: 'rgba(255,255,255,0.26)',
    fontSize: '0.6875rem',
    fontWeight: 400,
    margin: '0.1875rem 0 0',
    fontFamily: FONT,
    lineHeight: '0.9375rem',
  },
  settingsCard: {
    width: '100%',
    borderRadius: '0.75rem',
    background: '#1A1A1A',
    border: '1px solid rgba(255,255,255,0.10)',
    overflow: 'visible',
    boxSizing: 'border-box',
    boxShadow: '0 1px 0.25rem rgba(0,0,0,0.28)',
  },
  rowTitle: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: '0.875rem',
    fontWeight: 600,
    margin: '0 0 0.125rem',
    fontFamily: FONT,
    lineHeight: 1.25,
  },
  rowSubtitle: {
    color: 'rgba(255,255,255,0.38)',
    fontSize: '0.75rem',
    margin: 0,
    fontFamily: FONT,
    lineHeight: '0.9375rem',
    fontWeight: 400,
  },
  rowIcon: {
    width: '2.375rem',
    height: '2.375rem',
    borderRadius: '0.5625rem',
    background: 'rgba(255,255,255,0.07)',
    color: 'var(--primary-accent-color)',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownWrap: {
    position: 'relative',
    flexShrink: 0,
    minWidth: '10.9375rem',
    zIndex: 2,
  },
  dropdownButton: {
    width: '100%',
    height: '2.25rem',
    border: '1px solid rgba(255,255,255,0.10)',
    borderRadius: '0.5rem',
    color: '#FFFFFF',
    fontSize: '0.8125rem',
    fontWeight: 500,
    fontFamily: FONT,
    padding: '0 0.625rem 0 0.75rem',
    outline: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
    transition: 'background 0.12s, border-color 0.12s',
  },
  dropdownValue: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdownIcon: {
    color: 'rgba(255,255,255,0.45)',
    display: 'flex',
    flexShrink: 0,
    transition: 'transform 0.14s',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 'calc(100% + 0.3125rem)',
    left: 0,
    right: 0,
    maxHeight: '15rem',
    overflowY: 'auto',
    padding: '0.25rem',
    borderRadius: '0.625rem',
    background: '#1A1A1A',
    border: '1px solid rgba(255,255,255,0.12)',
    boxShadow: '0 1rem 3rem rgba(0,0,0,0.65)',
    zIndex: 30,
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255,255,255,0.10) transparent',
  },
  dropdownItem: {
    width: '100%',
    minHeight: '2rem',
    border: 'none',
    borderRadius: '0.4375rem',
    padding: '0.4375rem 0.625rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
    fontSize: '0.8125rem',
    fontWeight: 500,
    fontFamily: FONT,
    textAlign: 'left',
  },
  dropdownItemLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
