import type React from 'react';

export const NAV_RAIL_WIDTH = 104;

const FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", "Ubuntu", "Noto Sans", sans-serif';
export { FONT };

export const styles: Record<string, React.CSSProperties> = {
  screen: {
    height: '100%',
    background: '#0C0C0C',
    overflow: 'hidden',
    padding: `32px 48px 40px ${NAV_RAIL_WIDTH + 28}px`,
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: '268px 1fr',
    gap: 32,
    alignItems: 'stretch',
  },
  sidebar: {
    minWidth: 0,
    height: '100%',
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  sidebarTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 700,
    margin: '0 0 4px',
    fontFamily: FONT,
    lineHeight: 1,
    letterSpacing: '-0.025em',
  },
  sidebarSubtitle: {
    color: 'rgba(255,255,255,0.28)',
    fontSize: 10,
    margin: '0 0 18px 1px',
    fontFamily: FONT,
    lineHeight: 1.35,
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.09em',
  },
  content: {
    minWidth: 0,
    height: '100%',
    overflowY: 'auto',
    padding: '0 10px 96px 0',
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255,255,255,0.1) transparent',
  },
  categoryCard: {
    width: '100%',
  },
  categoryIcon: {
    width: 36,
    height: 36,
    borderRadius: 9,
    background: 'rgba(255,255,255,0.07)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  categoryLabel: {
    display: 'block',
    color: 'rgba(255,255,255,0.90)',
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: FONT,
  },
  categorySubtitle: {
    display: 'block',
    color: 'rgba(255,255,255,0.36)',
    fontSize: 11,
    lineHeight: '15px',
    fontWeight: 400,
    marginTop: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: FONT,
  },
  chevronIcon: {
    display: 'flex',
    color: 'rgba(255,255,255,0.22)',
    flexShrink: 0,
  },
  mobileDivider: {
    height: 1,
    background: 'rgba(255,255,255,0.045)',
    marginLeft: 58,
  },
  versionFooter: {
    color: 'rgba(255,255,255,0.25)',
    fontSize: 11,
    fontWeight: 400,
    fontFamily: FONT,
    textAlign: 'center',
    margin: '14px 0 0',
    letterSpacing: '0.04em',
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    minHeight: 36,
    marginBottom: 22,
    paddingBottom: 18,
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  detailTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 700,
    margin: 0,
    fontFamily: FONT,
    lineHeight: 1,
    letterSpacing: '-0.025em',
  },
  settingsGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    marginBottom: 24,
  },
  groupHeading: {
    paddingLeft: 4,
  },
  groupTitle: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 11,
    fontWeight: 600,
    margin: 0,
    fontFamily: FONT,
    textTransform: 'uppercase',
    letterSpacing: '0.07em',
  },
  groupSubtitle: {
    color: 'rgba(255,255,255,0.26)',
    fontSize: 11,
    fontWeight: 400,
    margin: '3px 0 0',
    fontFamily: FONT,
    lineHeight: '15px',
  },
  settingsCard: {
    width: '100%',
    borderRadius: 12,
    background: '#1A1A1A',
    border: '1px solid rgba(255,255,255,0.10)',
    overflow: 'visible',
    boxSizing: 'border-box',
    boxShadow: '0 1px 4px rgba(0,0,0,0.28)',
  },
  rowTitle: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 14,
    fontWeight: 600,
    margin: '0 0 2px',
    fontFamily: FONT,
    lineHeight: 1.25,
  },
  rowSubtitle: {
    color: 'rgba(255,255,255,0.38)',
    fontSize: 12,
    margin: 0,
    fontFamily: FONT,
    lineHeight: '15px',
    fontWeight: 400,
  },
  rowIcon: {
    width: 38,
    height: 38,
    borderRadius: 9,
    background: 'rgba(255,255,255,0.07)',
    color: 'var(--primary-accent-color)',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownWrap: {
    position: 'relative',
    flexShrink: 0,
    minWidth: 175,
    zIndex: 2,
  },
  dropdownButton: {
    width: '100%',
    height: 36,
    border: '1px solid rgba(255,255,255,0.10)',
    borderRadius: 8,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: FONT,
    padding: '0 10px 0 12px',
    outline: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    transition: 'background 0.12s, border-color 0.12s',
  },
  dropdownValue: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdownIcon: {
    color: 'rgba(255,255,255,0.45)',
    display: 'flex',
    flexShrink: 0,
    transition: 'transform 0.14s',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 'calc(100% + 5px)',
    left: 0,
    right: 0,
    maxHeight: 240,
    overflowY: 'auto',
    padding: 4,
    borderRadius: 10,
    background: '#1A1A1A',
    border: '1px solid rgba(255,255,255,0.12)',
    boxShadow: '0 16px 48px rgba(0,0,0,0.65)',
    zIndex: 30,
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255,255,255,0.10) transparent',
  },
  dropdownItem: {
    width: '100%',
    minHeight: 32,
    border: 'none',
    borderRadius: 7,
    padding: '7px 10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    fontSize: 13,
    fontWeight: 500,
    fontFamily: FONT,
    textAlign: 'left',
  },
  dropdownItemLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
