export type Tab = 'account' | 'general' | 'appearance' | 'playback' | 'content' | 'addons' | 'downloads';

export interface Prefs {
  language: string;
  startPage: string;
  backgroundPlayback: boolean;
  alertNewEpisodes: boolean;
  tmdbApiKey: string;
  tmdbCastImagesEnabled: boolean;
  tmdbSimilarResultsEnabled: boolean;
  tmdbTrailersEnabled: boolean;
  tmdbRecommendationsEnabled: boolean;
  tmdbCollectionInfoEnabled: boolean;
  tmdbEpisodeImagesEnabled: boolean;
  tmdbLogosBackdropsEnabled: boolean;
  tmdbRatingsEnabled: boolean;
  rpdbApiKey: string;
  omdbApiKey: string;
  fanartApiKey: string;
  accentColorArgb: string;
  animationsEnabled: boolean;
  gifAutoplayEnabled: boolean;
  cardCornerPreset: string;
  navLayout: string;
  navBarPosition: string;
  navItemsAlign: string;
  navSidebarMode: string;
  interfaceDensity: string;
  posterWidthPreset: string;
  posterLandscapeMode: boolean;
  posterHideTitles: boolean;
  cardLayout: string;
  continueWatchingLayout: string;
  continueWatchingArtwork: string;
  continueWatchingRemainingFormat: string;
  continueWatchingProgressDirection: string;
  continueWatchingEnabled: boolean;
  continueWatchingKeepScheduled: boolean;
  detailEpisodeViewMode: string;
  trailerOnHero: boolean;
  blurUnwatchedEpisodes: boolean;
  spoilerHideEpisodeInfo: boolean;
  continueWatchingHideTitles: boolean;
  showHeroSection: boolean;
  heroFeedToggles: string[];
  homeFeedToggles: string[];
  topTenFeedToggles: string[];
  preferredPlayer: string;
  mpvCustomOptions: string;
  animeUpscalingMode: string;
  frameInterpolationMode: string;
  streamSourceSelectionMode: string;
  streamSourceRegexPattern: string;
  autoPlayNextEpisode: boolean;
  autoPlayCountdownSecs: string;
  tryBingeGroup: boolean;
  nextEpisodeThresholdPercent: string;
  watchedThresholdPercent: string;
  playbackSpeed: string;
  seekSeconds: string;
  holdToSpeedEnabled: boolean;
  holdSpeed: string;
  playerBufferCacheMb: string;
  playerForwardBufferSeconds: string;
  playerBackBufferSeconds: string;
  audioDecoderMode: string;
  autoSkipIntro: boolean;
  useIntroDb: boolean;
  useAniSkip: boolean;
  useChapterSkip: boolean;
  preferredAudioLanguage: string;
  secondaryAudioLanguage: string;
  animePreferJapaneseAudio: boolean;
  preferredSubtitleLanguage: string;
  secondarySubtitleLanguage: string;
  autoEnableSubtitles: boolean;
  subtitleSize: string;
  subtitleColor: string;
  subtitleTextOpacity: string;
  subtitleBackgroundColor: string;
  subtitleBackgroundOpacity: string;
  subtitleOutlineColor: string;
  subtitleOutlineOpacity: string;
  downloadSourceSelectionMode: string;
  downloadSourceRegexPattern: string;
  downloadSubtitleLanguage: string;
  downloadDir: string;
  homeSeasonPostersOnHero: boolean;
  detailSeasonPostersOnHero: boolean;
  detailSeasonSelectorMode: string;
  episodeCardsLayout: string;
  heroFeedOrder: string[];
  homeFeedOrder: string[];
  pictureInPicture: boolean;
  notificationsEnabled: boolean;
  automaticUpdates: boolean;
  timezoneConversionEnabled: boolean;
  reduceMotion: boolean;
  subtitleShadow: boolean;
  seekThumbnailEnabled: boolean;
  p2pEnabled: boolean;
  discordRichPresenceEnabled: boolean;
  diagnosticMode: boolean;
  syncCwSourceOfTruth: string;
  syncCwRanking: string;
}

export interface TraktTokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  created_at: number;
}

export interface SyncMeta {
  lastSyncAt: number;
  continueWatchingCount: number;
  watchlistCount: number;
}

export const DEFAULT_PREFS: Prefs = {
  language: 'en',
  startPage: 'home',
  backgroundPlayback: false,
  alertNewEpisodes: true,
  tmdbApiKey: '',
  tmdbCastImagesEnabled: true,
  tmdbSimilarResultsEnabled: true,
  tmdbTrailersEnabled: true,
  tmdbRecommendationsEnabled: true,
  tmdbCollectionInfoEnabled: true,
  tmdbEpisodeImagesEnabled: true,
  tmdbLogosBackdropsEnabled: true,
  tmdbRatingsEnabled: true,
  accentColorArgb: '#FFFFFF',
  animationsEnabled: true,
  gifAutoplayEnabled: false,
  navLayout: 'sidebar',
  navBarPosition: 'left',
  navItemsAlign: 'center',
  navSidebarMode: 'hover',
  cardCornerPreset: 'soft',
  interfaceDensity: 'medium',
  posterWidthPreset: 'medium',
  posterLandscapeMode: false,
  posterHideTitles: false,
  cardLayout: 'vertical',
  continueWatchingLayout: 'horizontal',
  continueWatchingArtwork: 'episode',
  continueWatchingRemainingFormat: 'time',
  continueWatchingProgressDirection: 'remaining',
  continueWatchingEnabled: true,
  continueWatchingKeepScheduled: false,
  detailEpisodeViewMode: 'legacy',
  trailerOnHero: false,
  blurUnwatchedEpisodes: false,
  spoilerHideEpisodeInfo: false,
  continueWatchingHideTitles: false,
  showHeroSection: true,
  heroFeedToggles: [],
  homeFeedToggles: [],
  topTenFeedToggles: [],
  preferredPlayer: 'mpv',
  mpvCustomOptions: '',
  animeUpscalingMode: 'auto',
  frameInterpolationMode: 'off',
  streamSourceSelectionMode: 'manual',
  streamSourceRegexPattern: '',
  autoPlayNextEpisode: true,
  autoPlayCountdownSecs: '7',
  tryBingeGroup: false,
  nextEpisodeThresholdPercent: '85',
  watchedThresholdPercent: '90',
  playbackSpeed: '1.0',
  seekSeconds: '10',
  holdToSpeedEnabled: true,
  holdSpeed: '2.0',
  playerBufferCacheMb: '100',
  playerForwardBufferSeconds: '120',
  playerBackBufferSeconds: '30',
  audioDecoderMode: 'hw_prefer',
  autoSkipIntro: false,
  useIntroDb: true,
  useAniSkip: true,
  useChapterSkip: true,
  preferredAudioLanguage: 'none',
  secondaryAudioLanguage: 'none',
  animePreferJapaneseAudio: false,
  preferredSubtitleLanguage: 'none',
  secondarySubtitleLanguage: 'none',
  autoEnableSubtitles: true,
  subtitleSize: '100',
  subtitleColor: '#FFFFFF',
  subtitleTextOpacity: '1.0',
  subtitleBackgroundColor: '#000000',
  subtitleBackgroundOpacity: '0.5',
  subtitleOutlineColor: '#000000',
  subtitleOutlineOpacity: '1.0',
  downloadSourceSelectionMode: 'first',
  downloadSourceRegexPattern: '',
  downloadSubtitleLanguage: 'preferred',
  downloadDir: '',
  homeSeasonPostersOnHero: true,
  detailSeasonPostersOnHero: true,
  detailSeasonSelectorMode: 'tabs',
  episodeCardsLayout: 'standard',
  heroFeedOrder: [],
  homeFeedOrder: [],
  pictureInPicture: false,
  notificationsEnabled: true,
  automaticUpdates: true,
  timezoneConversionEnabled: true,
  reduceMotion: false,
  subtitleShadow: false,
  seekThumbnailEnabled: false,
  p2pEnabled: true,
  discordRichPresenceEnabled: true,
  diagnosticMode: false,
  rpdbApiKey: '',
  omdbApiKey: '',
  fanartApiKey: '',
  syncCwSourceOfTruth: 'most_recent',
  syncCwRanking: 'last_watched',
};
